name: julog
description: "A journaling application for youth firefighter groups focused on privacy and simplicity."
contributors:
  - pbarbenheim
license: GNU General Public License v3.0

publish_to: "none"

version: 1.0.0-beta.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  material_symbols_icons: ^4.2892.0
  shared_preferences: ^2.5.4
  vector_graphics: ^1.1.19
  jldb:
    git:
      url: https://github.com/pbarbenheim/jldb.git
      # TODO: Change to a specific tag or commit hash when releasing
      ref: main
  jlcrypto:
    git:
      url: https://github.com/pbarbenheim/jlcrypto.git
      # TODO: Change to a specific tag or commit hash when releasing
      ref: main
  file_selector: ^1.1.0
  freezed_annotation: ^3.1.0
  meta: ^1.17.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  go_router_builder: ^4.1.3
  build_runner: ^2.10.5
  build_verify: ^3.1.1
  riverpod_generator: ^4.0.0+1
  vector_graphics_compiler: ^1.1.19
  pubspec_extract: ^2.1.1
  freezed: ^3.2.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - path: assets/logo.svg
      transformers:
        - package: vector_graphics_compiler

pubspec_extract:
  destination: lib/pubspec.g.dart
